// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: protobuf/cube.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CubeName   string  `protobuf:"bytes,1,opt,name=cubeName,proto3" json:"cubeName,omitempty"`
	Key        string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value      []byte  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	GetterFunc *string `protobuf:"bytes,4,opt,name=getterFunc,proto3,oneof" json:"getterFunc,omitempty"` // optional getter lua script for specified key
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_cube_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_cube_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_cube_proto_rawDescGZIP(), []int{0}
}

func (x *SetValueRequest) GetCubeName() string {
	if x != nil {
		return x.CubeName
	}
	return ""
}

func (x *SetValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetValueRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetValueRequest) GetGetterFunc() string {
	if x != nil && x.GetterFunc != nil {
		return *x.GetterFunc
	}
	return ""
}

type SetValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_cube_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_cube_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_cube_proto_rawDescGZIP(), []int{1}
}

type GetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CubeName string `protobuf:"bytes,1,opt,name=cubeName,proto3" json:"cubeName,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_cube_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_cube_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_cube_proto_rawDescGZIP(), []int{2}
}

func (x *GetValueRequest) GetCubeName() string {
	if x != nil {
		return x.CubeName
	}
	return ""
}

func (x *GetValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_cube_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_cube_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_cube_proto_rawDescGZIP(), []int{3}
}

func (x *GetValueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetValueResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetValueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCubeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CubeName       string  `protobuf:"bytes,1,opt,name=cubeName,proto3" json:"cubeName,omitempty"`
	MaxBytes       int64   `protobuf:"varint,2,opt,name=maxBytes,proto3" json:"maxBytes,omitempty"`
	CubeGetterFunc *string `protobuf:"bytes,3,opt,name=cubeGetterFunc,proto3,oneof" json:"cubeGetterFunc,omitempty"` // optional default getter lua script for the cube
	OnEvictedFunc  *string `protobuf:"bytes,4,opt,name=onEvictedFunc,proto3,oneof" json:"onEvictedFunc,omitempty"`   // optional call-back lua script when key is evicted
	DelayWrite     *bool   `protobuf:"varint,5,opt,name=delayWrite,proto3,oneof" json:"delayWrite,omitempty"`        // use write-delay mode
}

func (x *CreateCubeRequest) Reset() {
	*x = CreateCubeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_cube_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCubeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCubeRequest) ProtoMessage() {}

func (x *CreateCubeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_cube_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCubeRequest.ProtoReflect.Descriptor instead.
func (*CreateCubeRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_cube_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCubeRequest) GetCubeName() string {
	if x != nil {
		return x.CubeName
	}
	return ""
}

func (x *CreateCubeRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *CreateCubeRequest) GetCubeGetterFunc() string {
	if x != nil && x.CubeGetterFunc != nil {
		return *x.CubeGetterFunc
	}
	return ""
}

func (x *CreateCubeRequest) GetOnEvictedFunc() string {
	if x != nil && x.OnEvictedFunc != nil {
		return *x.OnEvictedFunc
	}
	return ""
}

func (x *CreateCubeRequest) GetDelayWrite() bool {
	if x != nil && x.DelayWrite != nil {
		return *x.DelayWrite
	}
	return false
}

type CreateCubeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateCubeResponse) Reset() {
	*x = CreateCubeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_cube_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCubeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCubeResponse) ProtoMessage() {}

func (x *CreateCubeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_cube_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCubeResponse.ProtoReflect.Descriptor instead.
func (*CreateCubeResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_cube_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCubeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCubeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobuf_cube_proto protoreflect.FileDescriptor

var file_protobuf_cube_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x75, 0x62, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x62,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x62,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a,
	0x0a, 0x67, 0x65, 0x74, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x67, 0x65, 0x74, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e,
	0x63, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x62, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x62, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x52, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xfc, 0x01, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x62, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x62, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x61, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6d, 0x61, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0e, 0x63, 0x75, 0x62, 0x65,
	0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0e, 0x63, 0x75, 0x62, 0x65, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x46, 0x75,
	0x6e, 0x63, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x6f, 0x6e, 0x45, 0x76, 0x69, 0x63, 0x74,
	0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0d,
	0x6f, 0x6e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x88, 0x01, 0x01,
	0x12, 0x23, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x75, 0x62, 0x65, 0x47, 0x65,
	0x74, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6f, 0x6e, 0x45,
	0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x22, 0x48, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x75, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x62, 0x0a, 0x04, 0x43, 0x75, 0x62, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x03, 0x53, 0x65, 0x74,
	0x12, 0x10, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x46, 0x0a, 0x0b, 0x43, 0x75, 0x62, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x75, 0x62, 0x65, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x75, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x63, 0x75, 0x62, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_cube_proto_rawDescOnce sync.Once
	file_protobuf_cube_proto_rawDescData = file_protobuf_cube_proto_rawDesc
)

func file_protobuf_cube_proto_rawDescGZIP() []byte {
	file_protobuf_cube_proto_rawDescOnce.Do(func() {
		file_protobuf_cube_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_cube_proto_rawDescData)
	})
	return file_protobuf_cube_proto_rawDescData
}

var file_protobuf_cube_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_cube_proto_goTypes = []interface{}{
	(*SetValueRequest)(nil),    // 0: SetValueRequest
	(*SetValueResponse)(nil),   // 1: SetValueResponse
	(*GetValueRequest)(nil),    // 2: GetValueRequest
	(*GetValueResponse)(nil),   // 3: GetValueResponse
	(*CreateCubeRequest)(nil),  // 4: CreateCubeRequest
	(*CreateCubeResponse)(nil), // 5: CreateCubeResponse
}
var file_protobuf_cube_proto_depIdxs = []int32{
	2, // 0: Cube.Get:input_type -> GetValueRequest
	0, // 1: Cube.Set:input_type -> SetValueRequest
	4, // 2: CubeControl.CreateCube:input_type -> CreateCubeRequest
	3, // 3: Cube.Get:output_type -> GetValueResponse
	1, // 4: Cube.Set:output_type -> SetValueResponse
	5, // 5: CubeControl.CreateCube:output_type -> CreateCubeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_cube_proto_init() }
func file_protobuf_cube_proto_init() {
	if File_protobuf_cube_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_cube_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_cube_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_cube_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_cube_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_cube_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCubeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_cube_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCubeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_cube_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_protobuf_cube_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_cube_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobuf_cube_proto_goTypes,
		DependencyIndexes: file_protobuf_cube_proto_depIdxs,
		MessageInfos:      file_protobuf_cube_proto_msgTypes,
	}.Build()
	File_protobuf_cube_proto = out.File
	file_protobuf_cube_proto_rawDesc = nil
	file_protobuf_cube_proto_goTypes = nil
	file_protobuf_cube_proto_depIdxs = nil
}
